const axios = require('axios');
const fs = require('fs');
const FormData = require('form-data');
const path = require('path');

async function testConversation() {
  try {
    // We need an input audio file. We can use the one generated by test_tts.js
    const inputAudioPath = path.join(__dirname, 'output_audio.mp3');

    if (!fs.existsSync(inputAudioPath)) {
      console.log("No 'output_audio.mp3' found. Please run 'node test_tts.js' first to generate a sample.");
      return;
    }

    console.log("Using input audio:", inputAudioPath);

    const formData = new FormData();
    formData.append('audio', fs.createReadStream(inputAudioPath));

    console.log('Sending audio to /api/conversation...');
    const response = await axios.post('http://localhost:3000/api/conversation', formData, {
      headers: {
        ...formData.getHeaders(),
      },
      responseType: 'arraybuffer' // Expecting audio back
    });

    console.log('Conversation Success! Response status:', response.status);

    // Save the response audio
    const outputPath = path.join(__dirname, 'conversation_response.mp3');
    fs.writeFileSync(outputPath, response.data);
    console.log('Response audio saved to:', outputPath);

  } catch (error) {
    console.error('Conversation Error:', error.response ? error.response.data.toString() : error.message);
  }
}

testConversation();
